language: csharp

script:
  - xbuild /p:Configuration=Release-mono-compat KLog/KLog.sln

before_install:
  - chmod +x fetchNuGet.sh
  - ./fetchNuGet.sh
  - sudo apt-get install nunit-console

before_script:
  - nuget restore KLog/KLog.sln

after_script:
  - nunit-console KLog/UnitTests/bin/Release/UnitTests.dll