version: 0.1.{build}

configuration: Release

image: Visual Studio 2017

before_build:
  - cmd: beforeBuild.bat

artifacts:
  - path: KLog\KLog\bin\Release\KLog.dll
    name: KLog.dll
  - path: KLog\KLog.Web\bin\Release\KLog.Web.dll
    name: KLog.Web.dll
  - path: '**\KLog*.nupkg'

# PowerShell script to deploy to NuGet (runs after any unit tests, if they pass)
after_test:
  - ps: .\NuGet\pack.ps1

# Publish to NuGet
deploy:
  provider: NuGet
  api_key:
    secure: fy1qFrz8kHfWX2AnOMd2BuzLgDb2MMTj2JrryhAe4n84l2smPM4ohi9NRZZ0MAig
  artifact: /.*\.nupkg/
  on:
    branch: release